title: <p align="center"> Kavya Gaja </p>
logo: /assets/img/profile.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/gajakavya/">LinkedIn</a> |
  <a href="https://github.com/KavyaGaja">GitHub</a>

  </p>



theme: jekyll-theme-minimal
